### ISSUE TITLE
Zoom and lat/lng in map options

### ISSUE THREAD

**Issue by fionawhim** [CityOfBoston/vizwiz#24]
For the city council map, we want to specify a default zoom of 12 and a lat/lng of 42.3200, -71.1284.

Currently there is no configuration for these options (though the zoom seems to default to 12).

<img width="657" alt="screen shot 2018-03-21 at 4 52 58 pm" src="https://user-images.githubusercontent.com/260837/37736916-96148824-2d28-11e8-97f7-0cf075d33575.png">

**Comment by paylakatel** [comment]
Decided to leave lat/lng and zoom selections out of initial versions of vizwiz in an effort to keep user inputs as low as possible and because maps we're focused on re-creating are city-wide. Will re-visit this in later versions.

[This issue](https://github.com/CityOfBoston/vizwiz/issues/28) will ensure we have the proper defaults set for city-wide maps.
